sequenceDiagram
    autonumber
    actor User as MOH User
    participant Web as Website UI
    participant API as Backend API
    participant DB as Database

    User->>Web: Open Website
    User->>Web: Login(username, password)
    activate Web
    
    Web->>API: POST /moh/token
    activate API
    API->>DB: Check Credentials
    
    alt Login Fail
        DB-->>API: Invalid / Not Found
        API-->>Web: 401 Error
        Web-->>User: Display Error Message
        Note right of Web: Retry Login
    else Login Successful
        DB-->>API: Valid
        API-->>Web: 200 OK (Auth Token)
        Web->>API: GET /moh/dashboard/stats
        API->>DB: Fetch Dashboard Stats
        DB-->>API: Stats Data
        API-->>Web: Return Stats
        Web-->>User: View Dashboard
    end
    deactivate API
    deactivate Web
